export const PRODUCTS_BASEURL = '/api/products'
export const ORDERS_BASEURL = '/api/orders'
export const SHIPPING_BASEURL = '/api/shipping'
export const PAYMENTS_BASEURL = '/api/payments'
export const USER_BASEURL = '/api/me'
export const CART_BASEURL = '/api/cart'
export const ADMIN_BASEURL = '/api/admin'